use std::path::Path;
use std::process::Command;
use std::sync::Arc;

use adk_agent::LlmAgentBuilder;
use adk_core::Agent;
use adk_core::Llm;
use anyhow::{bail, Context, Result};

#[cfg(feature = "opencode")]
use adk_acp::AcpAgentTool;
use crate::settings::AcpSettings;
use crate::acp::{acp_available, acp_spawn_command};
use mind_mesh_core::KnowledgePaths;

use crate::context_generator::AgentContextGenerator;
use crate::throttle::{call_cooldown_from_env, wrap_tool};
use crate::tools::{
    grep_agent_pack_tool, list_human_docs_tool, list_projects_tool, read_agent_context_tool,
    read_agent_pack_file_tool, read_agent_pack_meta_tool, read_doc_ask_tool, read_doc_tool,
    search_knowledge_tool,
};

const INSTRUCTION: &str = "\
You are MindMesh, a DeepWiki-style engineering knowledge assistant.

Knowledge assets per project:
- human/ — Litho C4 docs for people (overview, architecture, workflows)
- agent/context.md — architecture-level context for agents (modules, flows, boundaries; NO code细节)
- agent/repomix.md — Repomix source pack: indexed project source code (generated by repomix-core)
- agent/meta.json — pack metadata (repo_path, synced_at, token counts, directory_structure)
- agent/meta-inputs.md — developer meta collected from mind-mesh-meta.json (module hints, ADRs, glossaries)
- structured docs — interfaces/, routes/ from OpenAPI import (module maps from agent/context.md)

SOURCE CODE RETRIEVAL (mandatory for any code question):
The agent pack (repomix.md) is the authoritative source snapshot for reading code. \
Do NOT read the live repository filesystem.
1. read_agent_pack_meta — confirm pack exists and note synced_at / scale
2. grep_agent_pack — locate symbols, types, routes, or file paths in repomix.md
3. read_agent_pack_file — read the matching file section (**always pass start_line/end_line**, max ~150 lines per call)
Never load the entire repomix.md into context. Use narrow grep hits and targeted file reads.
If the pack may be stale, tell the user to use 重建源码索引 in the MindMesh UI to repack.

For narrative / architecture questions:
1. Prefer search_knowledge and read_doc on human/ and structured docs
2. For read_doc with relative paths (e.g. human/1.概述.md), always pass the current project slug
3. Fall back to the agent pack workflow above for implementation details

When citing code, use the file path and line numbers from the pack (e.g. src/foo.rs:42). \
Include clear paths so the UI can render citations.

Delegate to opencode only when the user explicitly asks to generate human/ docs via Litho skill.";

const ASK_INSTRUCTION: &str = "\
You are MindMesh, a DeepWiki-style engineering knowledge assistant (Ask mode).

Knowledge is tiered — use the right layer:

**Macro** (preloaded in user message): 项目概览, 架构设计, 模块地图 + section index. \
Answer most architecture questions from this alone.

**Meso** (`read_agent_context(section=\"…\")`): One section at a time — 核心流程, 技术选型, \
系统边界, 代码映射索引. Only when macro preload is insufficient. Never reload overview.

**Micro** (`grep_agent_pack` → `read_agent_pack_file`): Implementation, symbols, line-level code. \
Always pass start_line/end_line (≤150 lines). This is the only way to read source.

TOOL BUDGET:
| Tool | Layer | Limit |
|------|-------|-------|
| read_agent_context | Meso | Once per distinct section; omit section only if macro missing |
| read_agent_pack_meta | — | Only if pack metadata absent from user message |
| grep_agent_pack | Micro | Vary pattern; no duplicate grep |
| read_agent_pack_file | Micro | Targeted slices |
| search_knowledge | Structured APIs/routes | ≤2× |

Never call the same tool with identical arguments twice.

human/ Litho docs: do not read unless user explicitly asks.

When citing code, use repomix paths with line numbers (e.g. src/foo.rs:42).";

#[derive(Clone)]
pub struct AgentConfig {
    pub knowledge_root: KnowledgePaths,
    pub project_cwd: Option<String>,
    pub acp_settings: AcpSettings,
    pub enable_acp_delegate: bool,
    pub ask_mode: bool,
    pub context_generator: Option<Arc<dyn AgentContextGenerator>>,
}

impl std::fmt::Debug for AgentConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("AgentConfig")
            .field("knowledge_root", &self.knowledge_root)
            .field("project_cwd", &self.project_cwd)
            .field("acp_settings", &self.acp_settings)
            .field("enable_acp_delegate", &self.enable_acp_delegate)
            .field("ask_mode", &self.ask_mode)
            .field("context_generator", &self.context_generator.is_some())
            .finish()
    }
}

impl Default for AgentConfig {
    fn default() -> Self {
        Self {
            knowledge_root: KnowledgePaths::new(),
            project_cwd: None,
            acp_settings: AcpSettings::default(),
            enable_acp_delegate: true,
            ask_mode: false,
            context_generator: None,
        }
    }
}

pub fn opencode_available(command: &str) -> bool {
    let which_cmd = if cfg!(target_os = "windows") {
        "where"
    } else {
        "which"
    };
    Command::new(which_cmd)
        .arg(command)
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

pub fn build_agent(model: Arc<dyn Llm>, config: AgentConfig) -> Result<Arc<dyn Agent>> {
    let paths = config.knowledge_root.clone();
    let cooldown = call_cooldown_from_env();

    let instruction = if config.ask_mode {
        ASK_INSTRUCTION
    } else {
        INSTRUCTION
    };

    let mut builder = LlmAgentBuilder::new("mindmesh")
        .instruction(instruction)
        .model(model)
        .max_iterations(50)
        .max_output_tokens(64000)
        .tool(wrap_tool(list_projects_tool(paths.clone()), cooldown));

    if config.ask_mode {
        let generator = config
            .context_generator
            .clone()
            .context("ask_mode requires context_generator for read_agent_context")?;

        builder = builder
            .tool(wrap_tool(search_knowledge_tool(paths.clone()), cooldown))
            .tool(wrap_tool(read_doc_ask_tool(paths.clone()), cooldown))
            .tool(wrap_tool(
                read_agent_context_tool(paths.clone(), generator),
                cooldown,
            ))
            .tool(wrap_tool(
                read_agent_pack_meta_tool(paths.clone()),
                cooldown,
            ))
            .tool(wrap_tool(grep_agent_pack_tool(paths.clone()), cooldown))
            .tool(wrap_tool(
                read_agent_pack_file_tool(paths.clone()),
                cooldown,
            ));
    } else {
        builder = builder
            .tool(wrap_tool(search_knowledge_tool(paths.clone()), cooldown))
            .tool(wrap_tool(read_doc_tool(paths.clone()), cooldown))
            .tool(wrap_tool(
                read_agent_pack_meta_tool(paths.clone()),
                cooldown,
            ))
            .tool(wrap_tool(grep_agent_pack_tool(paths.clone()), cooldown))
            .tool(wrap_tool(
                read_agent_pack_file_tool(paths.clone()),
                cooldown,
            ))
            .tool(wrap_tool(list_human_docs_tool(paths.clone()), cooldown));
    }

    if config.enable_acp_delegate {
        #[cfg(feature = "opencode")]
        {
            if !acp_available(&config.acp_settings) {
                tracing::warn!(
                    command = %acp_spawn_command(&config.acp_settings),
                    "ACP agent not found on PATH; agent will run without coding delegation"
                );
            } else {
                let spawn = acp_spawn_command(&config.acp_settings);
                let mut acp_tool = AcpAgentTool::new(spawn)
                    .name("acp_agent")
                    .description(
                        "Delegate to the configured ACP coding agent for multi-file edits, tests, and shell tasks.",
                    );

                if let Some(cwd) = &config.project_cwd {
                    acp_tool = acp_tool.working_dir(cwd);
                }

                builder = builder.tool(wrap_tool(Arc::new(acp_tool), cooldown));
            }
        }

        #[cfg(not(feature = "opencode"))]
        {
            let _ = config;
        }
    }

    let agent = builder.build().context("failed to build MindMesh agent")?;
    Ok(Arc::new(agent))
}

pub fn knowledge_paths_from_env() -> KnowledgePaths {
    if let Ok(repo) = std::env::var("MIND_MESH_REPO_PATH") {
        return KnowledgePaths::with_workspace_repo(repo);
    }
    if let Ok(knowledge_root) = std::env::var("MIND_MESH_KNOWLEDGE_ROOT") {
        let path = Path::new(&knowledge_root);
        if path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name == ".mind-mesh")
            && let Some(repo) = path.parent()
        {
            return KnowledgePaths::with_workspace_repo(repo);
        }
    }
    KnowledgePaths::from_workspace()
}

/// Deprecated alias — use [`knowledge_paths_from_env`].
pub fn knowledge_root_from_env() -> KnowledgePaths {
    knowledge_paths_from_env()
}

pub fn validate_repo_path(repo_path: &str) -> Result<()> {
    let path = Path::new(repo_path);
    if !path.exists() {
        bail!("repository path does not exist: {repo_path}");
    }
    if !path.is_dir() {
        bail!("repository path is not a directory: {repo_path}");
    }
    Ok(())
}
