// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentPackSummary = { total_files: number, total_tokens: number, output_path: string, };
