// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetGenerator } from "./AssetGenerator";
import type { TokenHeavyFile } from "./TokenHeavyFile";

export type AgentPackMeta = { project: string, repo_path: string, generator: AssetGenerator, 
/**
 * e.g. `architecture-context` — see docs/schema.md
 */
pack_strategy: string, output_file: string, total_files: number, total_tokens: number, total_characters: number, top_files_by_tokens: Array<TokenHeavyFile>, directory_structure: string, synced_at: string, 
/**
 * Git HEAD at pack time — used for freshness drift detection.
 */
baseline_git_head: string | null, };
