// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentContextMeta } from "./AgentContextMeta";
import type { KnowledgeRefreshMode } from "./KnowledgeRefreshMode";

export type AgentContextGenerationResult = { output_path: string, meta: AgentContextMeta, response_excerpt: string, refresh_mode: KnowledgeRefreshMode, };
