// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentContextStatus = { ready: boolean, path: string, excerpt: string | null, generated_at: string | null, section_count: number, };
