// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LlmStatus } from "./LlmStatus";
import type { ModelSettings } from "./ModelSettings";
import type { ProjectRegistryEntry } from "./ProjectRegistryEntry";

/**
 * Single IPC payload for app startup — avoids multiple round-trips on first paint.
 */
export type AppBootstrap = { model_settings: ModelSettings, registry_projects: Array<ProjectRegistryEntry>, llm_status: LlmStatus, acp_ok: boolean, };
