// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AskSessionInfo = { id: string, title: string, 
/**
 * Last assistant reply date (`YYYY-MM-DD`).
 */
last_replied_at: string, };
