// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssetGenerator = "litho-skill" | "repomix-core" | "git-scanner" | "open-api-importer";
