// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatPhase = "preparing_pack" | "preparing_context" | "thinking" | "tools" | "generating" | "streaming";
