// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Top-level document kinds stored under `{repo}/.terrain/`.
 */
export type DocType = "project" | "module" | "interface" | "route" | "event" | "human" | "agent_context";
