// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnvIntegrationStatus = { id: string, kind: string, label: string, description: string, integrated: boolean, optional: boolean, bundled: boolean, locked: boolean, depends_on: Array<string>, detail: string, };
