// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvPlanStep } from "./EnvPlanStep";

export type EnvPlan = { repo_path: string, selected_ids: Array<string>, steps: Array<EnvPlanStep>, skipped: Array<string>, };
