// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvIntegrationStatus } from "./EnvIntegrationStatus";

export type EnvStatus = { repo_path: string, ready_count: number, total_count: number, summary: string, items: Array<EnvIntegrationStatus>, };
