// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FreshnessDriftFactor } from "./FreshnessDriftFactor";

export type FreshnessSummary = { overall_score: number, overall_stale: boolean, commits_since_baseline: number, changed_files_count: number, current_git_head: string | null, working_tree_dirty: boolean, is_git_repo: boolean, last_computed_at: string, stale_reason: string | null, agent_pack_score: number, agent_context_score: number, human_docs_score: number, macro_preload_allowed: boolean, drift_factors: Array<FreshnessDriftFactor>, sample_changed_files: Array<string>, pack_baseline_short: string | null, context_baseline_short: string | null, };
