// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FreshnessDriftFactor = { id: string, 
/**
 * `high` | `medium` | `low` | `info`
 */
severity: string, title: string, detail: string, points_lost: number | null, };
