// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LithoStatus = { human_doc_count: number, has_human_docs: boolean, human_docs_complete: boolean, has_research_artifacts: boolean, };
