// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProgressKind = "project_init" | "scan" | "human_docs" | "agent_context" | "litho" | "sdd" | "env" | "quick_refresh" | "done";
