// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectSummary = { slug: string, name: string, path: string, repo_path: string | null, };
