// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FreshnessSummary } from "./FreshnessSummary";

/**
 * Result of scan + repack + optional agent context regeneration (desktop quick refresh).
 */
export type QuickRefreshResult = { project_slug: string, scan_files_written: number, pack_tokens: number | null, agent_context_regenerated: boolean, notes: Array<string>, freshness: FreshnessSummary, };
