// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UsageModelBreakdown = { model_name: string, input_tokens: number, output_tokens: number, cache_creation_tokens: number, cache_read_tokens: number, cost_usd: number, };
