// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentExecution } from "./AgentExecution";

export type AcpSettings = { binary: string | null, args: string | null, command: string | null, agent_execution: AgentExecution, auto_approve: boolean | null, };
