// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceCitation } from "./SourceCitation";
import type { TokenUsage } from "./TokenUsage";
import type { ToolCallRecord } from "./ToolCallRecord";

export type AskKnowledgeReply = { answer: string, citations: Array<SourceCitation>, tool_calls: Array<ToolCallRecord>, usage: TokenUsage, completed_at: number, };
