// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Plan for Agent + Litho skill to generate human-facing docs.
 */
export type LithoPlan = { project_slug: string, repo_path: string, skill_dir: string, human_output_dir: string, litho_workspace_dir: string, skill_ready: boolean, };
