// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LithoPlan } from "./LithoPlan";

export type LithoGenerationResult = { plan: LithoPlan, response_excerpt: string, human_doc_count: number, human_docs_complete: boolean, };
