// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectInitResult = { project_slug: string, repo_path: string, scan_files_written: number, repack_tokens: number | null, agent_context_generated: boolean, human_doc_count: number, human_docs_complete: boolean, litho_ran: boolean, notes: Array<string>, };
