// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CitationKind } from "./CitationKind";

export type SourceCitation = { kind: CitationKind, title: string, path: string, repo_path: string | null, start_line: number | null, end_line: number | null, excerpt: string | null, };
