// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatToolCallStatus } from "./ChatToolCallStatus";

export type ToolCallRecord = { id: string, name: string, arguments: Record<string, unknown>, result: unknown, error: string | null, status: ChatToolCallStatus, 
/**
 * Unix epoch milliseconds when the tool call started.
 */
started_at: number, completed_at: number, duration_ms: number, };
