/** DeepWiki Ask panel: sessions, sharing, sources, toasts. */
export default {
  canFollowUp: "Follow-ups welcome",
  noFinalAnswer:
    "Knowledge base search finished, but no final text reply was received. See the tool call results above.",
  errorPrefix: "Error: {error}",
  session: {
    new: "New conversation",
    newSession: "New chat",
    creating: "Creating…",
    history: "Ask history",
    historyTitle: "Ask History",
    recentCount: "Last {count} · Stored locally",
    empty: "No history yet",
    deleteThis: "Delete this conversation",
    deleteNamed: "Delete {title}",
    confirmDelete:
      'Delete conversation "{title}"?\n\nThis permanently deletes the Ask history and cannot be undone.',
  },
  notice: {
    title: "Ask reply finished",
    close: "Dismiss notification",
    expand: "Expand reply",
    open: "Open Ask",
  },
  toast: {
    copiedToClipboard: "Copied to clipboard",
    copyFailed: "Copy failed: {error}",
    imageCopied: "Image copied to clipboard",
    imageCopiedMulti:
      'Long answer — copied page 1 of {count}. Use "Export long image" to save all pages',
    exported: "Exported {count} image(s) to {dir}",
    exportedOmitted: " ({count} overlong block(s) omitted)",
    exportFailed: "Export failed: {error}",
    sessionCreated: "New conversation started",
    sessionCreateFailed: "Failed to create conversation: {error}",
    sessionSwitchFailed: "Failed to switch conversation: {error}",
    sessionDeleteFailed: "Failed to delete conversation: {error}",
  },
  export: {
    pickDir: "Choose export folder",
  },
  share: {
    questionLabel: "Question",
    continued: "Continued · {recap}",
    generatedBy: "Generated by Terrain",
  },
  sourcesLabel: "Sources",
  toolTrace: {
    arguments: "Arguments",
    result: "Result",
    waiting: "Waiting for result…",
    headerOne: "1 tool call",
    headerMany: "{count} tool calls",
  },
  usageLine: {
    template: "Tokens — input {input} · output {output}{suffix}",
    estimated: " (estimated)",
  },
  shareImage: {
    copyImage: "Copy image",
    copyTitle: "Copy as image (long answers copy page 1)",
    exportLong: "Export long image",
    exporting: "Exporting…",
    exported: "Exported",
    exportTitle: "Export as PNG (long answers are paginated)",
    omitted:
      'Answer too long — {count} more block(s) omitted. Use "Copy Markdown" for the full text.',
    canvasTooLarge: "Canvas too large ({width}×{height}); still cannot render after fallbacks",
    renderFailed: "Image rendering failed",
    renderRetry: "Image rendering failed, please try again later",
    unknownError: "Unknown error",
  },
  copyMarkdown: {
    label: "Copy Markdown",
    copying: "Copying…",
  },
  source: {
    lines: "Lines {start}–{end}",
    linesWithFocus: "Lines {start}–{end} · cited line {focus}",
    loading: "Loading…",
    loadFailed: "Could not load source file",
  },
} as const;
