/** Help-panel glossary entries (was `src/lib/glossary.ts`). */
export default {
  knowledgeTab: {
    term: "Knowledge",
    description:
      "Browse all knowledge assets under `.terrain/` in the repository — human-friendly and agent-friendly docs plus structured indexes.",
  },
  humanKnowledge: {
    term: "Human-friendly Knowledge Base",
    description:
      "C4 architecture docs generated by the Litho pipeline and stored under `human/` (e.g. 1.Overview, 2.Architecture), written for team reading and onboarding.",
  },
  agentKnowledge: {
    term: "Agent-friendly Knowledge Assets",
    description:
      "Dense architecture notes stored at paths like `agent/context.md` for Ask and coding agents (module map, core flows) — not long-form reading material.",
  },
  addAndInit: {
    term: "Add & Initialize",
    description:
      "After picking a local Git repository, Terrain automatically scans and indexes it, rebuilds the source index, and generates agent-friendly knowledge assets and the human-friendly knowledge base (depending on LLM / ACP configuration).",
  },
  rebuildIndex: {
    term: "Rebuild Source Index",
    description:
      "Repack the repository source into `agent/repomix.md` with Repomix so Ask and agents can look up code by path (not committed; safe to regenerate).",
  },
  ask: {
    term: "Ask",
    description:
      "DeepWiki-style chat grounded in the current project's knowledge assets and source index, with citations of doc fragments and code line numbers.",
  },
  quickRefresh: {
    term: "Quick Refresh",
    description:
      "Scan + rebuild the source index + regenerate agent-friendly knowledge assets (skips Litho). Use after code changes to reduce stale-knowledge misleading agents.",
  },
  freshness: {
    term: "Knowledge Freshness",
    description:
      "Compares git HEAD with the baseline commit recorded when the assets were generated and scores 0–100. Below 50, Ask will not preload the potentially stale architecture overview.",
  },
  agentEnv: {
    term: "Agent-ready Engineering Environment",
    description:
      "Integrates Skills, CodeGraph, RTK and AGENTS.md for coding agents like Cursor — independent from human knowledge base generation.",
  },
  structuredIndex: {
    term: "Structured Index",
    description:
      "Interface, route and event docs auto-imported from sources like OpenAPI, plus developer-maintained meta inputs.",
  },
  acp: {
    term: "ACP",
    description:
      "Agent Client Protocol agent (OpenCode by default). When the execution mode is ACP, Ask, context generation, SDD and Litho all run through the external agent + CLI + skills.",
  },
  llm: {
    term: "LLM",
    description:
      "Large language model connection (OpenAI-compatible / LM Studio / Ollama). Used for Ask, agent context generation and SDD document phases when the execution mode is Native.",
  },
  sdd: {
    term: "SDD Workflow",
    description:
      "Software-design-driven four-phase flow: requirements → tech design → implementation notes → code review. Outputs are stored locally under `~/.terrain/sdd/` (not committed to Git).",
  },
} as const;
