//! Run `cargo run -p terrain-ts-export --bin export-ts-types` to regenerate `src/lib/generated/`.

use std::fs;
use std::path::{Path, PathBuf};

use ts_rs::TS;

const EXPORT_DIR: &str = "../../src/lib/generated/";

fn export_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(EXPORT_DIR)
}

fn write_barrel_index(out: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let mut names: Vec<String> = fs::read_dir(out)?
        .filter_map(|e| e.ok())
        .filter_map(|e| {
            let name = e.file_name().to_string_lossy().into_owned();
            name.strip_suffix(".ts")
                .filter(|base| *base != "index")
                .map(str::to_string)
        })
        .collect();
    names.sort();

    let mut body = String::from(
        "// AUTO-GENERATED by `cargo run -p terrain-ts-export --bin export-ts-types`\n\
         // Do not edit manually — run `bun run gen:types` after changing Rust IPC types.\n\n",
    );
    for name in &names {
        body.push_str(&format!("export type {{ {name} }} from \"./{name}\";\n"));
    }
    fs::write(out.join("index.ts"), body)?;
    Ok(())
}

fn main() {
    if let Err(e) = run() {
        eprintln!("failed to export TypeScript types: {e}");
        std::process::exit(1);
    }
    println!("exported IPC types to src/lib/generated/");
}

fn run() -> Result<(), Box<dyn std::error::Error>> {
    let out = export_dir();
    fs::create_dir_all(&out)?;

    terrain_core::ProjectOverview::export_all_to(&out)?;
    terrain_core::AskSessionInfo::export_all_to(&out)?;
    terrain_core::EnvStatus::export_all_to(&out)?;
    terrain_core::ProjectSummary::export_all_to(&out)?;
    terrain_core::SearchHit::export_all_to(&out)?;
    terrain_core::ScanReport::export_all_to(&out)?;
    terrain_core::StaleProjectSummary::export_all_to(&out)?;
    terrain_core::QuickRefreshResult::export_all_to(&out)?;
    terrain_core::SourceSlice::export_all_to(&out)?;
    terrain_core::HumanDocEntry::export_all_to(&out)?;
    terrain_core::EnvPlan::export_all_to(&out)?;
    terrain_core::EnvApplyResult::export_all_to(&out)?;
    terrain_core::SddPhaseResult::export_all_to(&out)?;
    terrain_agent::LithoGenerationResult::export_all_to(&out)?;
    terrain_agent::ChatPhase::export_all_to(&out)?;
    terrain_agent::ChatReply::export_all_to(&out)?;
    terrain_agent::ProjectInitResult::export_all_to(&out)?;
    terrain_agent::LithoGenerationJob::export_all_to(&out)?;
    terrain_agent::ModelSettings::export_all_to(&out)?;
    terrain_agent::LlmStatus::export_all_to(&out)?;
    terrain_agent::AgentContextGenerationResult::export_all_to(&out)?;

    terrain_core::UsageSnapshot::export_all_to(&out)?;
    terrain_core::UsageProbeResult::export_all_to(&out)?;
    terrain_core::UsageDetailLevel::export_all_to(&out)?;

    write_barrel_index(&out)?;
    Ok(())
}
